/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    borderRadius: {
      "none": "0px",
      "xs": "0px",
      "sm": "0px",
      "DEFAULT": "0px",
      "md": "0px",
      "lg": "0px",
      "xl": "0px",
      "2xl": "0px",
      "3xl": "0px",
      "full": "0px",
      "btn": "0px",
      "card": "0px"
    },
    extend: {
      colors: {
        "surface-variant": "#fddbd6",
        "on-surface": "#291714",
        "tertiary-fixed-dim": "#9ecaff",
        "on-primary-fixed-variant": "#930005",
        "secondary-fixed": "#e2e2e2",
        "on-primary-fixed": "#410001",
        "river-black": "#000000",
        "secondary-container": "#e2e2e2",
        "surface-container": "#ffe9e6",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb4a9",
        "primary": "#ba0009",
        "inverse-primary": "#ffb4a9",
        "on-secondary-container": "#646464",
        "on-secondary": "#ffffff",
        "background": "#fff8f7",
        "river-white": "#ffffff",
        "on-secondary-fixed-variant": "#474747",
        "secondary-fixed-dim": "#c6c6c6",
        "surface-bright": "#fff8f7",
        "on-tertiary-fixed-variant": "#00497c",
        "inverse-surface": "#402b28",
        "on-secondary-fixed": "#1b1b1b",
        "on-background": "#291714",
        "surface-container-highest": "#fddbd6",
        "inverse-on-surface": "#ffedea",
        "outline": "#926f6a",
        "on-primary-container": "#fffaf9",
        "outline-variant": "#e7bdb7",
        "river-red": "#E2211C",
        "surface-container-low": "#fff0ee",
        "primary-container": "#e2211c",
        "secondary": "#5e5e5e",
        "tertiary-fixed": "#d1e4ff",
        "tertiary-container": "#0077c5",
        "on-error": "#ffffff",
        "tertiary": "#005e9d",
        "surface-tint": "#c00009",
        "on-surface-variant": "#5d3f3b",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface": "#fff8f7",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#001d36",
        "on-tertiary-container": "#fafaff",
        "primary-fixed": "#ffdad5",
        "surface-dim": "#f4d3ce",
        "surface-container-high": "#ffe2dd",
        "error-container": "#ffdad6"
      },
      spacing: {
        "spacing-40": "40px",
        "spacing-16": "16px",
        "spacing-4": "4px",
        "spacing-24": "24px",
        "spacing-8": "8px",
        "spacing-12": "12px"
      },
      fontFamily: {
        "body": ["Epilogue", "sans-serif"],
        "display": ["Epilogue", "sans-serif"],
        "heading-lg": ["Epilogue", "sans-serif"],
        "subheading": ["Epilogue", "sans-serif"],
        "caption": ["sans-serif"],
        "heading": ["Epilogue", "sans-serif"]
      },
      fontSize: {
        "body": ["15px", { lineHeight: "1.6", letterSpacing: "-0.022em", fontWeight: "400" }],
        "display": ["69px", { lineHeight: "1.13", letterSpacing: "-0.022em", fontWeight: "700" }],
        "heading-lg": ["34px", { lineHeight: "1.18", letterSpacing: "-0.022em", fontWeight: "700" }],
        "subheading": ["19px", { lineHeight: "1.26", letterSpacing: "-0.022em", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "1.2", letterSpacing: "-0.022em", fontWeight: "400" }],
        "heading": ["24px", { lineHeight: "1.33", letterSpacing: "-0.022em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
